### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fakerybakery** [OpenCodeInterpreter/OpenCodeInterpreter#1]
Hey, this looks really cool! Would you mind adding a license? Thanks!

**Comment by Zheng0428** [comment]
Hello!

Thank you for your interest and for reaching out. I'm pleased to let you know that we have updated our project with the Apache 2.0 license. You can now find the license file in the repository. This should address any concerns regarding the use and distribution of the project under open source terms.

**Comment by fakerybakery** [comment]
Thanks!
