### ISSUE TITLE
What is WizardCoder 110k dataset (mentioned in the paper) ?

### ISSUE THREAD

**Issue by yucc-leon** [OpenCodeInterpreter/OpenCodeInterpreter#10]
I cannot find it by search engine. Did you get this dataset from the author (WizardLM team) ?

**Comment by Zheng0428** [comment]
You can find the dataset at the following link: https://huggingface.co/datasets/ise-uiuc/Magicoder-Evol-Instruct-110K.

**Comment by yucc-leon** [comment]
> You can find the dataset at the following link: https://huggingface.co/datasets/ise-uiuc/Magicoder-Evol-Instruct-110K.

If so, the description might be misleading...Would you mind adding a URL in the footnote or renaming it as something else?

**Comment by Zheng0428** [comment]
> > You can find the dataset at the following link: https://huggingface.co/datasets/ise-uiuc/Magicoder-Evol-Instruct-110K.
> 
> If so, the description might be misleading...Would you mind adding a URL in the footnote or renaming it as something else?

You're absolutely correct, and we appreciate your attentiveness. We have just submitted an updated version of the paper, and you should be able to see this revised version in about two days. Thank you for your reminder.

**Comment by yucc-leon** [comment]
> > > You can find the dataset at the following link: https://huggingface.co/datasets/ise-uiuc/Magicoder-Evol-Instruct-110K.
> > 
> > 
> > If so, the description might be misleading...Would you mind adding a URL in the footnote or renaming it as something else?
> 
> You're absolutely correct, and we appreciate your attentiveness. We have just submitted an updated version of the paper, and you should be able to see this revised version in about two days. Thank you for your reminder.

My pleasure :). Looking forward to your updated version.
