### ISSUE TITLE
System error, Python version mismatch and triton==2.0.0 installation

### ISSUE THREAD

**Issue by nicekate** [OpenCodeInterpreter/OpenCodeInterpreter#12]
To get started with demo, 3.10 is installed, but when installing the required libraries, the following bug appears:

ERROR: Ignored the following versions that require a different python version: 1.6.2 Requires-Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10
ERROR: Could not find a version that satisfies the requirement triton==2.0.0 (from versions: none)
ERROR: No matching distribution found for triton==2.0.0

**Comment by AnitaLiu98** [comment]
Make sure to include the repository hosting Triton 2.0.0 in your package manager's sources. If it hasn't been added yet, the version you're seeking might not be accessible to your package manager.
