### ISSUE TITLE
[REQUEST] OpenCodeInterpreter version of Deepseek Coder 7B v1.5

### ISSUE THREAD

**Issue by savareyhano** [OpenCodeInterpreter/OpenCodeInterpreter#16]
I'm curious of how the result would be, as the claimed "SoTA for open-source models. On-par with GPT-4." [Gorilla OpenFunctions v2](https://huggingface.co/gorilla-llm/gorilla-openfunctions-v2) is using the Deepseek Coder 7B v1.5 as it's the base model (it's the instruct version though):

![Screenshot 2024-03-05 235304](https://github.com/OpenCodeInterpreter/OpenCodeInterpreter/assets/32730327/0e5e1449-d6ae-4a71-a866-e742348fa4d8)

Also thanks for creating a nice coding model for free and open source, the OpenCodeInterpreter DS 6.7B is my current favorite open source coding model so far (for the 7B coding models) as it's able to give a good answer to my most programming question where i ask in continuation.

**Comment by xiangyue9607** [comment]
Thanks! Our project mostly focuses on code generation and refinement, while OpenFunctions V2 focuses on function calling. You might directly reach out to them to ask your question! Thanks again for your interest in our OpenCI work!
