### ISSUE TITLE
Quantized 4 bit models ,gguf ..

### ISSUE THREAD

**Issue by MrBenzWorld** [OpenCodeInterpreter/OpenCodeInterpreter#3]
Could you please provide quantized models.

**Comment by wangfeng35** [comment]
There's already someone quantized models on the Huggingface.
[[OpenCodeInterpreter](https://huggingface.co/bartowski/OpenCodeInterpreter-CL-7B-exl2)](https://huggingface.co/models?search=OpenCodeInterpreter%20gguf)

**Comment by Zheng0428** [comment]
@wangfeng35, thank you for answering my question and pointing me towards the quantized models on Huggingface. I appreciate your help!
