### ISSUE TITLE
Can you provide the Gradio interface code in the demo video?

### ISSUE THREAD

**Issue by nicekate** [OpenCodeInterpreter/OpenCodeInterpreter#4]
expect

**Comment by Zheng0428** [comment]
We are currently in the final stages of adjustments for our demo and are excited to announce that we will be making our project available on Hugging Face Spaces next week. Stay tuned for the official release, and we appreciate your anticipation and support!

**Comment by nicekate** [comment]
> We are currently in the final stages of adjustments for our demo and are excited to announce that we will be making our project available on Hugging Face Spaces next week. Stay tuned for the official release, and we appreciate your anticipation and support!

The project is great. Thank you for replying.

**Comment by Zheng0428** [comment]
Hello! If you're looking to try out the OpenCodeInterpreter but aren't sure where to start, here's a simplified guide. First, if you have access to a GPU resource, like a 4090, you can download the model from the provided Hugging Face link: https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B. After downloading, you can test the model locally using the demo code provided on the same page. If you don't have the necessary resources, don't worry—the project will be open-sourced on Huggingface Spaces next week, where you'll be able to try the model without needing to download anything. Keep an eye on the project page for updates!

**Comment by nicekate** [comment]
I have downloaded 33b model using Ollama https://ollama.com/pxlksr/opencodeinterpreter-ds, but it does not interact with you in the demo video, so I still look forward to your official demo code on github. Thank you for your reply.

**Comment by wangfeng35** [comment]
can't waiting to see the demo

**Comment by Zheng0428** [comment]
@wangfeng35 We are currently in discussions with official representatives from Hugging Face regarding the matter. I believe the demo will be presented to everyone in the next couple of days.
