### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by fememystic** [OpenCodeInterpreter/OpenCodeInterpreter#5]
Hello! I'm just an enthusiast, not a programmer on anything. I know, it's a stupid question, but i have no idea how to download and install the programm. Could you please tell me, what should i do step by step to make it work? I see page: https://opencodeinterpreter.github.io/ . But i really don't understand what should i download... I would appreciate your help!

**Comment by PierrunoYT** [comment]
Same question here.

**Comment by heheheee21** [comment]
u have to use huggingface platform

**Comment by fememystic** [comment]
> u have to use huggingface platform

More details, please?

**Comment by heheheee21** [comment]
> > u have to use huggingface platform
> 
> 
> 
> More details, please?

https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B

idk am i right or not)
But as I understand, u should use this platform in some way 

u should search inf on YT

**Comment by fememystic** [comment]
> > > u have to use huggingface platform
> > 
> > 
> > More details, please?
> 
> https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B
> 
> idk am i right or not) But as I understand, u should use this platform in some way
> 
> u should search inf on YT

I found nothing on YT, this is why i asked here. Thank you, but it doesn't help

**Comment by Zheng0428** [comment]
Hello! If you're looking to try out the OpenCodeInterpreter but aren't sure where to start, here's a simplified guide. First, if you have access to a GPU resource, like a 4090, you can download the model from the provided Hugging Face link: https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B. After downloading, you can test the model locally using the demo code provided on the same page. If you don't have the necessary resources, don't worry—the project will be open-sourced on Huggingface Spaces next week, where you'll be able to try the model without needing to download anything. Keep an eye on the project page for updates!

**Comment by fememystic** [comment]
> Привет! Если вы хотите опробовать OpenCodeInterpreter, но не знаете, с чего начать, вот упрощенное руководство. Во-первых, если у вас есть доступ к ресурсу графического процессора, например 4090, вы можете загрузить модель по предоставленной ссылке Hugging Face: [https://huggingface.co/map/OpenCodeInterpreter-DS-6.7B](https://huggingface.co/m-a-p/OpenCodeInterpreter-DS-6.7B) . После загрузки вы можете протестировать модель локально, используя демонстрационный код, представленный на той же странице. Если у вас нет необходимых ресурсов, не волнуйтесь — на следующей неделе проект будет доступен на Huggingface Spaces с открытым исходным кодом, где вы сможете опробовать модель, не скачивая ничего. Следите за обновлениями на странице проекта!

Thank you. i have a good gpu, but the problem is - I don't understand how to use it, how to install, through what? I see the folder you linked me, but what should i do to launch it? This was my question

**Comment by Zheng0428** [comment]
Hi @fememystic ,
I came across a tool mentioned around the 9-minute mark in this YouTube video [link](https://www.youtube.com/watch?v=fqqlRZbYv5k&ab_channel=WorldofAI) that I believe could be very helpful for you.

**Comment by fememystic** [comment]
> Hi @fememystic , I came across a tool mentioned around the 9-minute mark in this YouTube video [link](https://www.youtube.com/watch?v=fqqlRZbYv5k&ab_channel=WorldofAI) that I believe could be very helpful for you.

Thank you. This is what i was trying to do, but getting the error
![image](https://github.com/OpenCodeInterpreter/OpenCodeInterpreter/assets/125194959/62e7547c-6d1f-46c2-8447-2b5d7e1fe2c6)

**Comment by Zheng0428** [comment]
> > Hi @fememystic , I came across a tool mentioned around the 9-minute mark in this YouTube video [link](https://www.youtube.com/watch?v=fqqlRZbYv5k&ab_channel=WorldofAI) that I believe could be very helpful for you.
> 
> Thank you. This is what i was trying to do, but getting the error ![image](https://private-user-images.githubusercontent.com/125194959/307711997-62e7547c-6d1f-46c2-8447-2b5d7e1fe2c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzU5MDUsIm5iZiI6MTcwODkzNTYwNSwicGF0aCI6Ii8xMjUxOTQ5NTkvMzA3NzExOTk3LTYyZTc1NDdjLTZkMWYtNDZjMi04NDQ3LTJiNWQ3ZTFmZTJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODFjMmViZmYxZjNmZDhmZTVmZTY0NzU5Mzg0NDZkNWUzYmU1Zjk3Y2U3OTA0YWRlMjQyYjAzODFiZDhhNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OOp6mIfIEzNVvd2HG95iRZAXLLPqfWlnOmYmeVLWt7s)

Could you tell me which GPU you have? The error suggests that your GPU may not meet the model's requirements.

**Comment by Zheng0428** [comment]
> > > > Hi @fememystic , I came across a tool mentioned around the 9-minute mark in this YouTube video [link](https://www.youtube.com/watch?v=fqqlRZbYv5k&ab_channel=WorldofAI) that I believe could be very helpful for you.
> > > 
> > > 
> > > Thank you. This is what i was trying to do, but getting the error ![image](https://private-user-images.githubusercontent.com/125194959/307711997-62e7547c-6d1f-46c2-8447-2b5d7e1fe2c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzU5MDUsIm5iZiI6MTcwODkzNTYwNSwicGF0aCI6Ii8xMjUxOTQ5NTkvMzA3NzExOTk3LTYyZTc1NDdjLTZkMWYtNDZjMi04NDQ3LTJiNWQ3ZTFmZTJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODFjMmViZmYxZjNmZDhmZTVmZTY0NzU5Mzg0NDZkNWUzYmU1Zjk3Y2U3OTA0YWRlMjQyYjAzODFiZDhhNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OOp6mIfIEzNVvd2HG95iRZAXLLPqfWlnOmYmeVLWt7s)
> > 
> > 
> > Could you tell me which GPU you have? The error suggests that your GPU may not meet the model's requirements.
> 
> rtx 3090. I generate images using very heavy sdxl models in stable diffusion, so it can't be a gpu problem

The RTX 3090 might have insufficient VRAM to run the full version of the 6.7B model. You could look for a quantized version of our model on Hugging Face. Try searching for our model's name along with 'quantized' or 'gguf' as keywords to find if someone has made a compatible version.

**Comment by fememystic** [comment]
> > > > > Hi @fememystic , I came across a tool mentioned around the 9-minute mark in this YouTube video [link](https://www.youtube.com/watch?v=fqqlRZbYv5k&ab_channel=WorldofAI) that I believe could be very helpful for you.
> > > > 
> > > > 
> > > > Thank you. This is what i was trying to do, but getting the error ![image](https://private-user-images.githubusercontent.com/125194959/307711997-62e7547c-6d1f-46c2-8447-2b5d7e1fe2c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5MzU5MDUsIm5iZiI6MTcwODkzNTYwNSwicGF0aCI6Ii8xMjUxOTQ5NTkvMzA3NzExOTk3LTYyZTc1NDdjLTZkMWYtNDZjMi04NDQ3LTJiNWQ3ZTFmZTJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNlQwODIwMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hODFjMmViZmYxZjNmZDhmZTVmZTY0NzU5Mzg0NDZkNWUzYmU1Zjk3Y2U3OTA0YWRlMjQyYjAzODFiZDhhNjMyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OOp6mIfIEzNVvd2HG95iRZAXLLPqfWlnOmYmeVLWt7s)
> > > 
> > > 
> > > Could you tell me which GPU you have? The error suggests that your GPU may not meet the model's requirements.
> > 
> > 
> > rtx 3090. I generate images using very heavy sdxl models in stable diffusion, so it can't be a gpu problem
> 
> The RTX 3090 might have insufficient VRAM to run the full version of the 6.7B model. You could look for a quantized version of our model on Hugging Face. Try searching for our model's name along with 'quantized' or 'gguf' as keywords to find if someone has made a compatible version.

24 VRAM is not enough?

**Comment by Zheng0428** [comment]
> 24 VRAM is not enough? Wow, ok, i'll check it. Thank you a lot and sorry for bothering!

It appears that 24 VRAM should actually be sufficient; my apologies for the misinformation, as I have never used a 3090 myself. Providing direct code and guiding you through the setup and other technical procedures might not be the best approach for you. I recommend continuing your search online for user-friendly tools, and perhaps sharing any useful findings here for the benefit of beginners. Thank you once again.

**Comment by fememystic** [comment]
> > 24 VRAM is not enough? Wow, ok, i'll check it. Thank you a lot and sorry for bothering!
> 
> It appears that 24 VRAM should actually be sufficient; my apologies for the misinformation, as I have never used a 3090 myself. Providing direct code and guiding you through the setup and other technical procedures might not be the best approach for you. I recommend continuing your search online for user-friendly tools, and perhaps sharing any useful findings here for the benefit of beginners. Thank you once again.

Gotcha. Thank you!

**Comment by fememystic** [comment]
> > 24 VRAM is not enough? Wow, ok, i'll check it. Thank you a lot and sorry for bothering!
> 
> It appears that 24 VRAM should actually be sufficient; my apologies for the misinformation, as I have never used a 3090 myself. Providing direct code and guiding you through the setup and other technical procedures might not be the best approach for you. I recommend continuing your search online for user-friendly tools, and perhaps sharing any useful findings here for the benefit of beginners. Thank you once again.

"It's because you are seeing incompatabile files that don't work in LM Studio. These models haven't been turned into GGUF quants so they will not work at all in LM Studio." This is what a guy from LM Studio support answered. So how do i use the models? :D

**Comment by wdonno** [comment]
For testing, would CoLab be an option?  Will take a look.

**Comment by Zheng0428** [comment]
> For testing, would CoLab be an option? Will take a look.

We will be updating the code deployed in the demo today, so please stay tuned.

**Comment by wdonno** [comment]
Wonderful!

> > For testing, would CoLab be an option? Will take a look.
> 
> We will be updating the code deployed in the demo today, so please stay tuned.
