### ISSUE TITLE
OpenAI - deprecated API?

### ISSUE THREAD

**Issue by TheodorosGalanos** [OpenCodeInterpreter/OpenCodeInterpreter#7]
Hello, noticed that you're not using the new 1.0 openai api. This is becoming deprecated, an update to 1.0 would be helpful

**Comment by Magnetic2014** [comment]
Thank you for expressing interest in our project! We will consider your input. Nonetheless, it will not be prioritized at this time, as the current 0.x version continues to meet our needs effectively.
